version: '3'

services:
  jenkins:
    image: nekronrt/jenkins:lts
    user: root
    container_name: jenkins
    ports:
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/jenkins_home:/var/jenkins_home
